######################################################################
# Automatically generated by qmake (3.1) Fri Jul 5 12:11:56 2024
######################################################################

QT+=widgets
QT+=charts
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += Utils/RandomGenerator.h \
           Utils/SensorItem.h \
           Utils/StringHelper.h \
           Utils/TimeHelper.h \
           Utils/TypeEnum.h \
           Utils/TypeHelper.h \
           Model/Managers/SaveLoadManager.h \
           Model/Managers/SensorManager.h \
           Model/NotificationSystem/Notification.h \
           Model/NotificationSystem/NotificationCreator.h \
           Model/Query/Query.h \
           Model/Query/QueryResults.h \
           Model/Query/QueryRunner.h \
           Model/Query/SensorScoreDecorator.h \
           Model/Query/TextQueryVisitor.h \
           Model/Query/TypeQueryChecker.h \
           Model/SaveLoad/JsonDistributionVisitor.h \
           Model/SaveLoad/JsonReader.h \
           Model/SaveLoad/JsonSensorVisitor.h \
           Model/SaveLoad/ObjectConverter.h \
           Model/Sensors/GroundSensor.h \
           Model/Sensors/HumiditySensor.h \
           Model/Sensors/SmokeSensor.h \
           Model/Sensors/SolarSensor.h \
           Model/Sensors/TemperatureSensor.h \
           Model/Sensors/WindSensor.h \
           Model/User/ColorSchemeEnum.h \
           Model/User/DataEncrypt.h \
           Model/User/UserData.h \
           Model/User/UserDataLoader.h \
           Model/Query/Strategy/QueryStrategy.h \
           Model/Query/Strategy/TextQueryStrategy.h \
           Model/Query/Strategy/TypeQueryStrategy.h \
           Model/Sensors/Core/AbstractSensor.h \
           Model/Sensors/Core/AlertSensor.h \
           Model/Sensors/Core/InfoSensor.h \
           Model/Sensors/Distributions/AbstractDistribution.h \
           Model/Sensors/Distributions/ExponentialDistribution.h \
           Model/Sensors/Distributions/NormalDistribuition.h \
           Model/Sensors/Distributions/RandomDistribution.h \
           Model/Sensors/Distributions/UniformDistribution.h \
           Model/Sensors/VisitorTypes/DistributionTypeVisitor.h \
           Model/Sensors/VisitorTypes/DistributionTypeVisitorConst.h \
           Model/Sensors/VisitorTypes/SensorClassVisitor.h \
           Model/Sensors/VisitorTypes/SensorClassVisitorConst.h \
           Model/Sensors/VisitorTypes/SensorTypeVisitor.h \
           Model/Sensors/VisitorTypes/SensorTypeVisitorConst.h
SOURCES += test.cpp \
           Utils/StringHelper.cpp \
           Utils/TimeHelper.cpp \
           Utils/TypeHelper.cpp \
           Model/Managers/SaveLoadManager.cpp \
           Model/Managers/SensorManager.cpp \
           Model/NotificationSystem/NotificationCreator.cpp \
           Model/Query/Query.cpp \
           Model/Query/QueryResults.cpp \
           Model/Query/QueryRunner.cpp \
           Model/Query/SensorScoreDecorator.cpp \
           Model/Query/TextQueryVisitor.cpp \
           Model/Query/TypeQueryChecker.cpp \
           Model/SaveLoad/JsonDistributionVisitor.cpp \
           Model/SaveLoad/JsonReader.cpp \
           Model/SaveLoad/JsonSensorVisitor.cpp \
           Model/SaveLoad/ObjectConverter.cpp \
           Model/Sensors/GroundSensor.cpp \
           Model/Sensors/HumiditySensor.cpp \
           Model/Sensors/SmokeSensor.cpp \
           Model/Sensors/SolarSensor.cpp \
           Model/Sensors/TemperatureSensor.cpp \
           Model/Sensors/WindSensor.cpp \
           Model/User/DataEncrypt.cpp \
           Model/User/UserData.cpp \
           Model/User/UserDataLoader.cpp \
           Model/Query/Strategy/TextQueryStrategy.cpp \
           Model/Query/Strategy/TypeQueryStrategy.cpp \
           Model/Sensors/Core/AbstractSensor.cpp \
           Model/Sensors/Core/AlertSensor.cpp \
           Model/Sensors/Core/InfoSensor.cpp \
           Model/Sensors/Distributions/AbstractDistribution.cpp \
           Model/Sensors/Distributions/ExponentialDistribution.cpp \
           Model/Sensors/Distributions/NormalDistribuition.cpp \
           Model/Sensors/Distributions/RandomDistribution.cpp \
           Model/Sensors/Distributions/UniformDistribuition.cpp
